version: "3.8"

services:


  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: linkedin-keycloak
    command: start-dev --import-realm
    ports:
      - "8080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json

  redis:
    image: redis:7
    container_name: linkedin-redis
    ports:
      - "6379:6379"

  postgres-search:
    image: postgres:16
    container_name: linkedin-search-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: searchdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - search_postgres_data:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.2.8
    container_name: linkedin-elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"

  search-discovery-service:
    build: ./backend/searchAndDiscover
    container_name: linkedin-search-discovery-service
    ports:
      - "8086:8086"
    depends_on:
      - postgres-search
      - elasticsearch
      - keycloak
      - redis
    environment:
      POSTGRES_URL: ${POSTGRES_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ELASTICSEARCH_URI: ${ELASTICSEARCH_URI}
      KEYCLOAK_ISSUER_URI: ${KEYCLOAK_ISSUER_URI}
      KEYCLOAK_JWK_SET_URI: ${KEYCLOAK_JWK_SET_URI}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      SWAGGER_OAUTH_CLIENT_ID: ${SWAGGER_OAUTH_CLIENT_ID}
      SWAGGER_OAUTH_REDIRECT_URL: ${SEARCH_SWAGGER_OAUTH_REDIRECT_URL}

  api-gateway:
    build: ./backend/api-gateway
    container_name: linkedin-api-gateway
    ports:
      - "8085:8085"
    depends_on:
      - keycloak
      - redis
      - search-discovery-service
      - userprofile-service
    environment:
      KEYCLOAK_ISSUER_URI: http://keycloak:8080/realms/linkedin-app
      REDIS_HOST: redis
      USERPROFILE_SERVICE_URI: http://userprofile-service:8083
      SEARCH_SERVICE_URI: http://search-discovery-service:8086
      FEED_SERVICE_URI: http://feed-and-timeline-service:8087

  userprofile-postgres:
    image: postgres:16
    container_name: linkedin-userprofile-postgres
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: userprofile
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hasnain4890
    volumes:
      - userprofile_postgres_data:/var/lib/postgresql/data


  userprofile-service:
    build: ./backend/userprofile
    container_name: linkedin-userprofile-service
    ports:
      - "8083:8083"
    depends_on:
      - userprofile-postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://userprofile-postgres:5432/userprofile
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: hasnain4890

  postgres-feed:
    image: postgres:16
    container_name: linkedin-feed-postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: feeddb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - feed_postgres_data:/var/lib/postgresql/data

  feed-and-timeline-service:
    build: ./backend/feedAndTimeline
    container_name: linkedin-feed-and-timeline-service
    ports:
      - "8087:8087"
    depends_on:
      - postgres-feed
      - keycloak
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres-feed:5432/feeddb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      KEYCLOAK_ISSUER_URI: http://localhost:8080/realms/linkedin-app
      KEYCLOAK_JWK_SET_URI: http://host.docker.internal:8080/realms/linkedin-app/protocol/openid-connect/certs
      SWAGGER_OAUTH_CLIENT_ID: linkedin-frontend
      SWAGGER_OAUTH_REDIRECT_URL: http://localhost:8087/swagger-ui/oauth2-redirect.html


  client:
    build: ./frontend
    container_name: linkedin-frontend
    ports:
      - "3000:3000"

    depends_on:
      - keycloak
      - api-gateway
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  feed_postgres_data:
  search_postgres_data:
  userprofile_postgres_data:






