spring:
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> c4e713a82e1baa1ee93fdb436c56d7991ad51579
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/linkedin-app
<<<<<<< HEAD
=======
  application:
    name: feedAndTimeline
>>>>>>> main
=======
>>>>>>> c4e713a82e1baa1ee93fdb436c56d7991ad51579
