ALTER TABLE posts
    ADD COLUMN IF NOT EXISTS author_avatar_url VARCHAR(512);

CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    author_id VARCHAR(255),
    author_name VARCHAR(255),
    content VARCHAR(5000) NOT NULL,
    created_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS post_likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    user_id VARCHAR(255) NOT NULL,
    created_at TIMESTAMP,
    CONSTRAINT uk_post_like_post_user UNIQUE (post_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_comments_post_id
    ON comments (post_id);

CREATE INDEX IF NOT EXISTS idx_post_likes_post_id
    ON post_likes (post_id);
