server:
  port: 8083

spring:
  application:
    name: userprofile-service

  datasource:
    url: jdbc:postgresql://userprofile-postgres:5432/userprofile
    username: postgres
    password: hasnain4890
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

  endpoint:
    health:
      show-details: always