spring:
  application:
    name: userprofile

  datasource:
    url: jdbc:postgresql://localhost:5432/userprofile
    username: postgres
    password: your_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
<<<<<<< HEAD
  port: 8082
=======
  port: 8080
>>>>>>> c4e713a82e1baa1ee93fdb436c56d7991ad51579
