server:
  port: 8085

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/linkedin-app
          jwk-set-uri: http://host.docker.internal:8080/realms/linkedin-app/protocol/openid-connect/certs

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: search-discovery-service-route
              uri: http://search-discovery-service:8086
              predicates:
                - Path=/api/search/**,/api/discovery/**

            - id: feed-root-route
              uri: http://feed-and-timeline-service:8087
              predicates:
                - Path=/api/feed

            - id: feed-posts-route
              uri: http://feed-and-timeline-service:8087
              predicates:
                - Path=/api/feed/**

management:
  endpoint:
    gateway:
      access: unrestricted

  endpoints:
    web:
      exposure:
        include: health,info,gateway