server:
  port: 8085

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/linkedin-clone

  data:
    redis:
      host: localhost
      port: 6379

  cloud:
    gateway:
      routes:
        - id: search-discovery-service-route
          uri: http://search-discovery-service:8086
          predicates:
            - Path=/api/search/**,/api/discovery/**
          filters:
            - name: CircuitBreaker
              args:
                name: searchDiscoveryCircuitBreaker
                fallbackUri: forward:/fallback/search-discovery

            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1

            - AddResponseHeader=X-Service-Name, search-discovery-service
            - AddResponseHeader=X-Gateway-Cache-Strategy, redis-cache-for-public-search-results

        - id: profile-service-route
          uri: http://profile-service:8081
          predicates:
            - Path=/api/profiles/**
          filters:
            - name: CircuitBreaker
              args:
                name: profileCircuitBreaker
                fallbackUri: forward:/fallback/profile

            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                redis-rate-limiter.requestedTokens: 1

        - id: post-service-route
          uri: http://post-service:8082
          predicates:
            - Path=/api/posts/**
          filters:
            - name: CircuitBreaker
              args:
                name: postCircuitBreaker
                fallbackUri: forward:/fallback/posts

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway