<<<<<<< HEAD
server:
  port: 8086

spring:
  application:
    name: search-discovery-service

  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/searchdb}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  elasticsearch:
    uris: ${ELASTICSEARCH_URI:http://localhost:9200}

=======
spring:
>>>>>>> c4e713a82e1baa1ee93fdb436c56d7991ad51579
  security:
    oauth2:
      resourceserver:
        jwt:
<<<<<<< HEAD
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/linkedin-app}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
=======
          issuer-uri: http://localhost:8080/realms/linkedin-app
>>>>>>> c4e713a82e1baa1ee93fdb436c56d7991ad51579
