spring:
  application:
    name: payment
  datasource:
    url: jdbc:postgresql://localhost:5433/paymentdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: localhost:9092
server:
  port: 8090