spring:
  application:
    name: payment
  datasource:
    url: jdbc:postgresql://localhost:5433/paymentdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
server:
  port: 8090

resilience4j:
  retry:
    instances:
      paymentProvider:
        max-attempts: 3
        wait-duration: 500ms
        retry-exceptions:
          - java.lang.RuntimeException
  circuitbreaker:
    instances:
      paymentProvider:
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2

stripe:
  secret-key: ${STRIPE_SECRET_KEY:}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET:}
