name: Build and Deploy

on:
  push:
    branches: [ dev, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - backend/api-gateway
          - backend/searchAndDiscover
          - backend/feedAndTimeline

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build and test
        working-directory: ${{ matrix.service }}
        run: mvn clean verify